SB-23980: Print Preview for images - Toast when PDF Generation begins and Blueprint updates
Sunbird-Ed/creation-portal pull request #1342
Opened 2021-05-11 14:40 UTC by bharatkashyap

<table>
<td>
  <a href="https://project-sunbird.atlassian.net/browse/SB-23980" title="SB-23980" target="_blank"><img alt="Task" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10318&avatarType=issuetype" />SB-23980</a>  Enhance print preview service to include support for Images
  </td></table>
  <br />
 

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

### Type of change

Please choose appropriate options.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How Has This Been Tested?

Please describe the tests that you ran to verify your changes in the below checkboxes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- No new tests have been written to test this. I have added a toast on the user's click on the "Print Preview" button. This also updates the existing functionality to filter topics and learningOutcomes while creating blueprints and change the number of question dropdown into a text value.

**Test Configuration**:
* Software versions: Angular 8, Nodejs 12.16.1
* Hardware versions:

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2021-05-11 15:36 UTC, pallakartheekreddy commented
@bharatkashyap did you verified these changes in local? and is it working fine?

2021-05-11 15:37 UTC, pallakartheekreddy requested changes

2021-05-11 15:37 UTC, pallakartheekreddy commented on src/app/resourcebundles/data/consumption/en.properties
> +messages.imsg.generatingPreview = Generating PDF. Please wait a while...
@bharatkashyap Please follow the same format how other messages are there. Please don't introduce a new format it will lead to confusion.

2021-05-11 16:07 UTC, bharatkashyap commented
> @bharatkashyap did you verified these changes in local? and is it working fine?

Yes @pallakartheekreddy - verified locally

2021-05-13 08:45 UTC, bharatkashyap commented
@SaketSinha @ChakshuGautam - can review please

2021-05-17 06:18 UTC, pallakartheekreddy approved these changes

2021-05-17 06:18 UTC, merged