Resource library integration
Sunbird-Ed/creation-portal pull request #1569
Opened 2021-09-15 05:10 UTC by manojSRawat

2021-09-15 15:38 UTC, pallakartheekreddy requested changes

2021-09-15 15:38 UTC, pallakartheekreddy commented on src/app/client/src/app/modules/sourcing/components/chapter-list/chapter-list.component.ts
> +      searchFormConfig: [
Why is this Config hardcoded? shouldn't it come from API?

2021-09-15 15:38 UTC, pallakartheekreddy commented on src/app/client/src/app/modules/sourcing/components/chapter-list/chapter-list.component.ts
> +            ]
Why is this Config required for a library?

2021-09-16 04:30 UTC, manojSRawat commented on src/app/client/src/app/modules/sourcing/components/chapter-list/chapter-list.component.ts
> +            ]
on the basis of objectType, we are getting the detail of questionSet/collection in the library.

2021-09-17 08:52 UTC, pallakartheekreddy commented on src/app/client/src/app/modules/sourcing/components/chapter-list/chapter-list.component.ts
> +            ]
@manojSRawat if the library already making apical why Config hardcoded?

2021-09-18 04:55 UTC, pallakartheekreddy approved these changes

2021-09-18 04:55 UTC, merged