Interactive Video V1 JIRA key-> SB-26330
Sunbird-Ed/creation-portal pull request #1599
Opened 2021-09-22 12:23 UTC by Harithaa95

[SB-26330](https://project-sunbird.atlassian.net/browse/SB-26330) Interactive Video V1

2021-09-22 13:51 UTC, venkateshwarans commented on src/app/client/src/app/modules/sourcing/services/quml-player/quml-player.service.ts
> +                        }
please add error check to get nested properties. for example: use `_.get(res[0], 'result.questionSet')` and `_.get(res[1], 'result.questionset.instructions')`

2021-09-22 13:52 UTC, venkateshwarans commented on src/app/client/src/app/modules/sourcing/components/content-uploader/content-uploader.component.spec.ts
> +  /***********************************************/
remove these lines

2021-09-22 13:53 UTC, venkateshwarans commented on src/app/client/src/app/modules/sourcing/components/content-uploader/content-uploader.component.html
> +                        </div> -->
remove the commented lines

2021-09-22 13:54 UTC, venkateshwarans commented on src/app/client/src/app/app.module.ts
> +    SunbirdVideoPlayerModule,
we don't have to import the video player module at the app level. only in sourcing module is enough

2021-09-22 13:55 UTC, venkateshwarans commented on src/app/client/src/app/modules/shared/services/config/app.config.json
> +          "lastName": "Dey"
can you make the userData as empty object?

2021-09-22 13:56 UTC, venkateshwarans commented on src/app/client/src/app/modules/sourcing/components/content-uploader/content-uploader.component.html
> +<!-- /****************************************************/ -->
please move these asterisk lines everywhere

2021-09-22 13:58 UTC, venkateshwarans commented on src/app/client/src/app/modules/sourcing/components/content-uploader/content-uploader.component.html
> +<sui-modal *ngIf="showquestionCreationUploadModal" [mustScroll]="true" [isClosable]="true" [transitionDuration]="0" [size]="'normal'"
please maintain consistency in naming variables. use proper camelCase for `showquestionCreationUploadModal`. make it `showQuestionCreationUploadModal`

2021-09-22 13:59 UTC, venkateshwarans commented on src/app/client/src/app/modules/sourcing/components/content-uploader/content-uploader.component.ts
> +  questionSetEditorComponentInput?: any;
we only need `questionSetEditorComponentInput` inside `IDynamicInput`. please remove the rest of the properties.

2021-09-22 14:00 UTC, venkateshwarans commented on src/app/client/src/app/modules/sourcing/components/content-uploader/content-uploader.component.ts
> +  // };
Please remove the commented out code

2021-09-22 14:04 UTC, venkateshwarans commented on src/app/client/src/app/modules/sourcing/components/content-uploader/content-uploader.component.ts
> +              'primaryCategory': "Demo Practice Question Set",
@Harithaa95  are we going to hardcode the primaryCategory as `Demo Practice Question Set`? 
CC @pallakartheekreddy

2021-09-22 14:14 UTC, venkateshwarans commented on src/app/client/src/app/modules/sourcing/components/content-uploader/content-uploader.component.ts
> +      this.playerConfigSunbird.context.cdata = _.get(this.sessionContext, 'telemetryPageDetails.telemetryInteractCdata') || [];
Any particular reason to rename the `this.playerConfig` variable? Can you revert back to `this.playerConfig`?

2021-09-22 14:17 UTC, venkateshwarans commented on src/app/client/package.json
> +    "@project-sunbird/sunbird-video-player-v9": "4.3.0",
Please change all the library package versions to recent versions. For example - you are downgrading  `@project-sunbird/sunbird-collection-editor-v9` from  `4.3.18` to `4.3.7`. keep it as `4.3.18`. and do the same of the rest

2021-09-22 14:19 UTC, venkateshwarans requested changes
Lots of changes required. And quite of lot of unnecessary code has been introduced to `content-uploader.compontent.ts`. please move them and make sure we test locally before pushing the changes.

2021-09-23 04:18 UTC, Harithaa95 commented on src/app/client/src/app/modules/sourcing/components/content-uploader/content-uploader.component.ts
> +      this.playerConfigSunbird.context.cdata = _.get(this.sessionContext, 'telemetryPageDetails.telemetryInteractCdata') || [];
Already playerConfig Variable is there and used by contentuploader component. So introduced new variable for question set editor.

2021-10-21 03:51 UTC, closed without merging