#SB-26662 feat: Increase the content size limit to 150 MB
Sunbird-Ed/creation-portal pull request #1604
Opened 2021-09-29 11:05 UTC by santoshilimi

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

### Type of change

Please choose appropriate options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How Has This Been Tested?

Please describe the tests that you ran to verify your changes in the below checkboxes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Ran Test A
- [ ] Ran Test B

**Test Configuration**:
* Software versions: Angular 8, Nodejs 12.16.1
* Hardware versions:

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-09-29 11:22 UTC, vaivk369 commented on src/app/client/src/app/modules/sourcing/components/resource-template/resource-template.component.ts
> +    const defaultfileSize =   _.get(this.selectedtemplateDetails, 'objectMetadata.config.sourcingConfig.defaultfileSize');
@santoshilimi can you test if this works when you open the draft content?

2021-09-29 11:31 UTC, santoshilimi commented on src/app/client/src/app/modules/sourcing/components/resource-template/resource-template.component.ts
> +    const defaultfileSize =   _.get(this.selectedtemplateDetails, 'objectMetadata.config.sourcingConfig.defaultfileSize');
Yes , i will test

2021-09-30 10:58 UTC, pallakartheekreddy requested changes

2021-09-30 10:58 UTC, pallakartheekreddy commented on src/app/client/src/index.html
> +  <% if (dock_default_file_size) { %>
@santoshilimi create a variable in the camel case.

2021-09-30 13:03 UTC, pallakartheekreddy approved these changes

2021-09-30 13:41 UTC, merged