Sneha nd/feat
Sunbird-Ed/creation-portal pull request #1813
Opened 2021-12-07 08:40 UTC by snehar-nd

Needed to add migrationStatus,  migrationError, quesionRefId fields, because 
migrationStatus: true/false, 
migrationError: "error message,
 quesionRefId :"old question id"

2021-12-07 08:44 UTC, snehar-nd commented
@pallakartheekreddy  please review and merge .

2021-12-10 10:29 UTC, pallakartheekreddy requested changes

2021-12-10 10:29 UTC, pallakartheekreddy commented on kp_schemas/question/1.0/schema.json
> +    "quesionRefId": {
CHange this field name `origin`

2021-12-10 11:33 UTC, snehar-nd commented on kp_schemas/question/1.0/schema.json
> +    "quesionRefId": {
okay

2021-12-13 06:54 UTC, pallakartheekreddy approved these changes

2021-12-13 06:54 UTC, merged