[Draft] Refactor 1.0
Sunbird-Ed/creation-portal pull request #1815
Opened 2021-12-07 18:54 UTC by manojSRawat

Please choose appropriate options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How Has This Been Tested?

Please describe the tests that you ran to verify your changes in the below checkboxes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Ran Test A
- [ ] Ran Test B

**Test Configuration**:
* Software versions: Angular 8, Nodejs 12.16.1
* Hardware versions:

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-12-22 06:26 UTC, venkateshwarans commented on src/app/client/src/app/modules/shared-feature/components/resource-template/resource-template.component.html
> +    <div *ngIf="!programContext.target_collection_category.includes('Exam Question Set')" class="d-flex flex-dc">
Can you avoid hard coding `Exam Question Set` or any primary categories

2021-12-22 06:33 UTC, venkateshwarans commented on src/app/client/src/app/modules/program/components/create-program/create-program.component.ts
> +    const objType = _.replace(_.lowerCase(selectedTargetCollectionObject?.targetObjectType), ' ', '');
Why is the replace function required here?

2021-12-22 06:44 UTC, venkateshwarans commented on src/app/client/src/app/modules/program/components/create-program/create-program.component.ts
> +      this.showTexbooklist(true);
Looks like we are not using the boolean parameter? What is the use of `if else` here?

2021-12-22 06:49 UTC, venkateshwarans commented on src/app/client/src/app/modules/program/components/create-program/create-program.component.ts
> +      else { // Update already selected questionset during project creation
How will this work in the existing flow because we don't `else` currently.

2021-12-22 06:51 UTC, venkateshwarans commented on src/app/client/src/app/modules/program/components/program-nominations/program-nominations.component.ts
> +    if (!this.programDetails.target_type || _.includes(['collections', 'questionSets'], this.programDetails.target_type)) {
can you make similar check like `_.includes(['collections', 'questionSets']` in other files as well instead of `this.projectTargetType === 'collections' || this.projectTargetType === 'questionSets'`

2021-12-22 06:56 UTC, venkateshwarans commented on src/app/client/src/app/modules/sourcing/components/chapter-list/chapter-list.component.ts
> +          _.forEach( _.get(response, 'result.Question'), (obj) => {
Are we getting `Question` as a separate object in the response?

2021-12-22 07:00 UTC, venkateshwarans commented on src/app/client/src/app/modules/sourcing/components/chapter-list/chapter-list.component.ts
> +      if ((this.checkifContent(data) && ( (this.myOrgId === data.organisationId) || (this.currentRootOrgID === _.get(data, 'channel'))))  && (!data.sampleContent || data.sampleContent === undefined))
Please make sure all the existing scenarios have also been verified.

2021-12-22 07:02 UTC, venkateshwarans commented on src/app/client/src/app/modules/sourcing/components/chapter-list/chapter-list.component.ts
> +      param: { 'mode': 'edit', 'fields': 'versionKey' }
Why have you removed `acceptedContents` from read api?

2021-12-22 07:05 UTC, venkateshwarans requested changes
Please check comments

2021-12-24 12:52 UTC, dhruvarya9654 commented on src/app/client/src/app/modules/sourcing/components/chapter-list/chapter-list.component.ts
> +          _.forEach( _.get(response, 'result.Question'), (obj) => {
Yes

2021-12-24 12:58 UTC, manojSRawat commented on src/app/client/src/app/modules/sourcing/components/chapter-list/chapter-list.component.ts
> +      param: { 'mode': 'edit', 'fields': 'versionKey' }
We are only updating `reusedContributions` key, so no need to fetch the `acceptedContents`.

2021-12-24 13:30 UTC, dhruvarya9654 commented on src/app/client/src/app/modules/program/components/create-program/create-program.component.ts
> +      this.showTexbooklist(true);
We have removed this parameter from function definition and also from function calls.

2021-12-24 13:56 UTC, dhruvarya9654 commented on src/app/client/src/app/modules/program/components/create-program/create-program.component.ts
> +    const objType = _.replace(_.lowerCase(selectedTargetCollectionObject?.targetObjectType), ' ', '');
We have removed this.

2021-12-24 14:10 UTC, dhruvarya9654 commented on src/app/client/src/app/modules/program/components/program-nominations/program-nominations.component.ts
> +    if (!this.programDetails.target_type || _.includes(['collections', 'questionSets'], this.programDetails.target_type)) {
We have done the changes

2021-12-24 15:06 UTC, dhruvarya9654 commented on src/app/client/src/app/modules/sourcing/components/chapter-list/chapter-list.component.ts
> +      if ((this.checkifContent(data) && ( (this.myOrgId === data.organisationId) || (this.currentRootOrgID === _.get(data, 'channel'))))  && (!data.sampleContent || data.sampleContent === undefined))
Sure

2021-12-24 15:31 UTC, dhruvarya9654 commented on src/app/client/src/app/modules/shared-feature/components/resource-template/resource-template.component.html
> +    <div *ngIf="!programContext.target_collection_category.includes('Exam Question Set')" class="d-flex flex-dc">
Resolved

2021-12-24 18:00 UTC, dhruvarya9654 commented on src/app/client/src/app/modules/program/components/create-program/create-program.component.ts
> +      else { // Update already selected questionset during project creation
`else` condition is executed when we edit and update an existing `questionset` during project creation

2021-12-27 09:31 UTC, pallakartheekreddy commented on src/app/client/src/app/modules/program/components/create-program/create-program.component.ts
> +    const objType = _.replace(_.lowerCase(selectedTargetCollectionObject?.targetObjectType), ' ', '');
in which scenario we are getting extra space?

2021-12-27 11:00 UTC, dhruvarya9654 commented on src/app/client/src/app/modules/program/components/create-program/create-program.component.ts
> +    const objType = _.replace(_.lowerCase(selectedTargetCollectionObject?.targetObjectType), ' ', '');
`_.lowerCase` method produces the extra space. For example `_.lowerCase('QuestionSet')` will return `question set`. To make the resulting value `questionset`, we used `_.replace` function

2021-12-30 12:11 UTC, merged